modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/webbukkit/dynmap/issues"
license="Apache Public License v2"
[[mods]]
modId="dynmapblockscan"
version="${version}"
displayName="DynmapBlockScan"
authors="mikeprimm"
description='''
Generate block render definitions for Dynmap
'''

[[dependencies.dynmap]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="SERVER"
[[dependencies.dynmap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="SERVER"
